// src/lib/scenarios.ts

export interface ScenarioStep {
  stepIndex: number;
  source: string; // node id
  target: string; // node id
  senderName: string; // organization name (e.g. Buyer AI COO)
  receiverName: string; // organization name (e.g. Supplier Alpha AI COO)
  dialogue: string; // AI dialogue message
  capability: 'Identity' | 'Routing' | 'Context Share' | 'Permission' | 'Briefing' | 'Heartbeat';
  reason: string; // why the task moved
  action: string; 
  narration: string;
  apiCallName: string;
  apiCallMethod: 'POST' | 'GET' | 'DELETE';
  apiCallPath: string;
  payload: any;
  glowNode: string;
  pulseType: 'message' | 'context' | 'share' | 'revoke' | 'complete';
  badge?: string;
}

export interface Scenario {
  id: string;
  name: string;
  description: string;
  steps: ScenarioStep[];
}

export const SCENARIOS: Scenario[] = [
  {
    id: "multi-supplier-procurement",
    name: "Scenario 1: Multi-Supplier Coordination",
    description: "Buyer AI COO coordinates with Supplier Alpha (60 available) and Supplier Beta (40 available) to fulfill a 100-unit requisition.",
    steps: [
      {
        stepIndex: 0,
        source: "customer",
        target: "support",
        senderName: "Customer Client",
        receiverName: "Buyer AI COO",
        dialogue: "Submitting requisition: 100 Industrial Steel Girders bound for Munich Facility.",
        capability: "Identity",
        reason: "Procurement request submitted.",
        action: "Customer places order for 100 Industrial Steel Girders.",
        narration: "Procurement request submitted for 100 Industrial Steel Girders.",
        apiCallName: "POST /api/v1/init",
        apiCallMethod: "POST",
        apiCallPath: "/init",
        payload: { workspace: "buyer_co_mesh" },
        glowNode: "support",
        pulseType: "message",
        badge: "Order Submitted"
      },
      {
        stepIndex: 1,
        source: "support",
        target: "partner",
        senderName: "Buyer AI COO",
        receiverName: "Supplier Alpha AI COO",
        dialogue: "Checking stock availability. Sharing folder context for requisition matching.",
        capability: "Context Share",
        reason: "Inventory check",
        action: "Buyer AI COO shares context and queries Supplier Alpha stock levels.",
        narration: "Buyer AI COO shares context and queries Supplier Alpha stock levels.",
        apiCallName: "POST /api/v1/share/create",
        apiCallMethod: "POST",
        apiCallPath: "/share/create",
        payload: { scope: "folders", folderIds: [2], label: "Quotation logs context" },
        glowNode: "partner",
        pulseType: "share",
        badge: "Alpha Query"
      },
      {
        stepIndex: 2,
        source: "partner",
        target: "support",
        senderName: "Supplier Alpha AI COO",
        receiverName: "Buyer AI COO",
        dialogue: "Inventory check complete: Only 60 Industrial Steel Girders are currently in stock.",
        capability: "Routing",
        reason: "Partial fulfillment",
        action: "Supplier Alpha returns stock count of 60 girders.",
        narration: "Supplier Alpha returns stock count of 60 girders.",
        apiCallName: "POST /api/v1/accumulate",
        apiCallMethod: "POST",
        apiCallPath: "/accumulate",
        payload: { files: [{ path: "Alpha/stock.md", content: "60 units available" }] },
        glowNode: "support",
        pulseType: "message",
        badge: "60 Available"
      },
      {
        stepIndex: 3,
        source: "support",
        target: "ceo",
        senderName: "Buyer AI COO",
        receiverName: "Supplier Beta AI COO",
        dialogue: "Deficit of 40 units detected. Querying backup supplier for remaining balance.",
        capability: "Context Share",
        reason: "Secondary inventory check",
        action: "Buyer AI COO queries backup Supplier Beta for the remaining 40 girders.",
        narration: "Buyer AI COO queries backup Supplier Beta for the remaining 40 girders.",
        apiCallName: "POST /api/v1/share/create",
        apiCallMethod: "POST",
        apiCallPath: "/share/create",
        payload: { scope: "folders", folderIds: [3], label: "Secondary quotation logs context" },
        glowNode: "ceo",
        pulseType: "share",
        badge: "Beta Query"
      },
      {
        stepIndex: 4,
        source: "ceo",
        target: "support",
        senderName: "Supplier Beta AI COO",
        receiverName: "Buyer AI COO",
        dialogue: "Verification complete: 40 Industrial Steel Girders allocated and reserved.",
        capability: "Routing",
        reason: "Secondary fulfillment",
        action: "Supplier Beta reserves 40 girders to satisfy order requirement.",
        narration: "Supplier Beta reserves 40 girders to satisfy order requirement.",
        apiCallName: "POST /api/v1/accumulate",
        apiCallMethod: "POST",
        apiCallPath: "/accumulate",
        payload: { files: [{ path: "Beta/stock.md", content: "40 units allocated" }] },
        glowNode: "support",
        pulseType: "message",
        badge: "40 Allocated"
      },
      {
        stepIndex: 5,
        source: "support",
        target: "operations",
        senderName: "Buyer AI COO",
        receiverName: "Logistics AI COO",
        dialogue: "Requisition satisfied. Please optimize route for consolidated shipping.",
        capability: "Permission",
        reason: "Delivery optimization",
        action: "Buyer AI COO dispatches logistics and shipping consolidation commands.",
        narration: "Buyer AI COO dispatches logistics and shipping consolidation commands.",
        apiCallName: "POST /api/v1/tools",
        apiCallMethod: "POST",
        apiCallPath: "/tools",
        payload: { tool: "schedule_shipping", params: { mode: "consolidated" } },
        glowNode: "operations",
        pulseType: "message",
        badge: "Route Sched"
      },
      {
        stepIndex: 6,
        source: "operations",
        target: "legal",
        senderName: "Logistics AI COO",
        receiverName: "Insurance AI COO",
        dialogue: "Consolidated cargo routes scheduled. Requesting transit insurance coverage.",
        capability: "Routing",
        reason: "Shipment coverage",
        action: "Logistics AI COO initiates insurance coverage for the combined cargo.",
        narration: "Logistics AI COO initiates insurance coverage for the combined cargo.",
        apiCallName: "POST /api/v1/chat",
        apiCallMethod: "POST",
        apiCallPath: "/chat",
        payload: { message: "Approve cargo transit insurance coverage" },
        glowNode: "legal",
        pulseType: "context",
        badge: "Insurance Req"
      },
      {
        stepIndex: 7,
        source: "legal",
        target: "customer",
        senderName: "Insurance AI COO",
        receiverName: "Customer Client",
        dialogue: "Transit insurance approved. Combined order of 100 Girders scheduled for dispatch.",
        capability: "Briefing",
        reason: "Procurement requisition complete",
        action: "Insurance AI COO reports delivery confirmation updates to Customer Client.",
        narration: "Insurance AI COO reports delivery confirmation updates to Customer Client.",
        apiCallName: "POST /api/v1/briefing",
        apiCallMethod: "POST",
        apiCallPath: "/briefing",
        payload: { summary: "100 Steel Girders scheduled for consolidated delivery" },
        glowNode: "customer",
        pulseType: "complete",
        badge: "Confirmed"
      }
    ]
  },
  {
    id: "high-value-procurement",
    name: "Scenario 2: High-Value Review",
    description: "Purchase exceeds $1,000,000 threshold. Buyer AI COO generates an Aicoo Briefing and requests human approval.",
    steps: [
      {
        stepIndex: 0,
        source: "customer",
        target: "support",
        senderName: "Customer Client",
        receiverName: "Buyer AI COO",
        dialogue: "Placing requisition: Superconducting MRI Components ($1,400,000). Priority Delivery.",
        capability: "Identity",
        reason: "High-value requisition submitted.",
        action: "Customer requests superconducting MRI components ($1,400,000).",
        narration: "Customer requests superconducting MRI components ($1,400,000).",
        apiCallName: "POST /api/v1/init",
        apiCallMethod: "POST",
        apiCallPath: "/init",
        payload: {},
        glowNode: "support",
        pulseType: "message",
        badge: "High-Val Order"
      },
      {
        stepIndex: 1,
        source: "support",
        target: "partner",
        senderName: "Buyer AI COO",
        receiverName: "Supplier Alpha AI COO",
        dialogue: "Verifying supplier capability and loading slots for MRI hardware.",
        capability: "Context Share",
        reason: "Verify supplier capability",
        action: "Buyer AI COO requests technical documentation access from Supplier Alpha.",
        narration: "Buyer AI COO requests technical documentation access from Supplier Alpha.",
        apiCallName: "POST /api/v1/share/create",
        apiCallMethod: "POST",
        apiCallPath: "/share/create",
        payload: { scope: "folders", folderIds: [2], label: "MRI production capability" },
        glowNode: "partner",
        pulseType: "share",
        badge: "Capability Check"
      },
      {
        stepIndex: 2,
        source: "partner",
        target: "support",
        senderName: "Supplier Alpha AI COO",
        receiverName: "Buyer AI COO",
        dialogue: "Production capability verified. Sourcing invoice generated: $1,400,000.",
        capability: "Routing",
        reason: "Verify contract pricing guidelines",
        action: "Supplier Alpha returns invoice details for contract review.",
        narration: "Supplier Alpha returns invoice details for contract review.",
        apiCallName: "POST /api/v1/accumulate",
        apiCallMethod: "POST",
        apiCallPath: "/accumulate",
        payload: { files: [{ path: "Alpha/mri-invoice.md", content: "INV-9008 value $1,400,000" }] },
        glowNode: "support",
        pulseType: "message",
        badge: "$1.4M Invoice"
      },
      {
        stepIndex: 3,
        source: "support",
        target: "support",
        senderName: "Buyer AI COO",
        receiverName: "Buyer AI COO",
        dialogue: "Security Alert: Order exceeds autonomous threshold of $1,000,000. Compiling Aicoo Briefing dossier.",
        capability: "Briefing",
        reason: "Autonomous limit exceeded",
        action: "Buyer AI COO flags order for human executive sign-off.",
        narration: "Buyer AI COO flags order for human executive sign-off, compiling Aicoo Briefing data.",
        apiCallName: "POST /api/v1/briefing",
        apiCallMethod: "POST",
        apiCallPath: "/briefing",
        payload: {},
        glowNode: "support",
        pulseType: "context",
        badge: "Human Handoff"
      },
      {
        stepIndex: 4,
        source: "support",
        target: "billing",
        senderName: "Buyer AI COO",
        receiverName: "Finance AI COO",
        dialogue: "Executive signature verified. Releasing funds to Finance AI COO for wire confirmation.",
        capability: "Permission",
        reason: "Manual review cleared",
        action: "Human approval registered. Transaction forwarded to Finance.",
        narration: "Human approval registered. Transaction forwarded to Finance.",
        apiCallName: "POST /api/v1/tools",
        apiCallMethod: "POST",
        apiCallPath: "/tools",
        payload: { tool: "release_wire_payment", params: { amount: 1400000 } },
        glowNode: "billing",
        pulseType: "complete",
        badge: "Approved"
      },
      {
        stepIndex: 5,
        source: "billing",
        target: "customer",
        senderName: "Finance AI COO",
        receiverName: "Customer Client",
        dialogue: "Wire transfer confirmed. Sourcing complete. Manufacturing scheduled.",
        capability: "Briefing",
        reason: "Order cleared for dispatch",
        action: "Finance AI COO clears payment terms and notifies Customer.",
        narration: "Finance AI COO clears payment terms and notifies Customer.",
        apiCallName: "POST /api/v1/briefing",
        apiCallMethod: "POST",
        apiCallPath: "/briefing",
        payload: { summary: "Payment wire received. Manufacturing of MRI components scheduled." },
        glowNode: "customer",
        pulseType: "complete",
        badge: "Cleared"
      }
    ]
  },
  {
    id: "supplier-outage-recovery",
    name: "Scenario 3: Outage Recovery",
    description: "Supplier Alpha drops offline. Network Monitor alerts Buyer, who automatically redirects request to Supplier Beta.",
    steps: [
      {
        stepIndex: 0,
        source: "customer",
        target: "support",
        senderName: "Customer Client",
        receiverName: "Buyer AI COO",
        dialogue: "Submitting requisition: 200 Monocrystalline Solar Panels bound for Tokyo Harbor.",
        capability: "Identity",
        reason: "Requisition submitted.",
        action: "Customer requests 200 Solar Panels.",
        narration: "Customer requests 200 Solar Panels.",
        apiCallName: "POST /api/v1/init",
        apiCallMethod: "POST",
        apiCallPath: "/init",
        payload: {},
        glowNode: "support",
        pulseType: "message",
        badge: "Requisition Recd"
      },
      {
        stepIndex: 1,
        source: "support",
        target: "partner",
        senderName: "Buyer AI COO",
        receiverName: "Supplier Alpha AI COO",
        dialogue: "Sending primary inquiry to Supplier Alpha. Awaiting stock count response.",
        capability: "Context Share",
        reason: "Verify primary stock",
        action: "Buyer AI COO requests quote from Supplier Alpha.",
        narration: "Buyer AI COO requests quote from Supplier Alpha.",
        apiCallName: "POST /api/v1/share/create",
        apiCallMethod: "POST",
        apiCallPath: "/share/create",
        payload: { scope: "folders", folderIds: [2], label: "Primary quotation logs context" },
        glowNode: "partner",
        pulseType: "share",
        badge: "Alpha Query"
      },
      {
        stepIndex: 2,
        source: "partner",
        target: "partner",
        senderName: "Supplier Alpha AI COO",
        receiverName: "Supplier Alpha AI COO",
        dialogue: "Connection Timeout. Heartbeat checks report: Supplier Alpha unavailable.",
        capability: "Heartbeat",
        reason: "Supplier Alpha unavailable",
        action: "Network Monitor logs outage on Supplier Alpha.",
        narration: "Network Monitor logs outage on Supplier Alpha.",
        apiCallName: "GET /api/v1/context/status",
        apiCallMethod: "GET",
        apiCallPath: "/context/status",
        payload: {},
        glowNode: "partner",
        pulseType: "revoke",
        badge: "ALPHA OUTAGE"
      },
      {
        stepIndex: 3,
        source: "support",
        target: "ceo",
        senderName: "Buyer AI COO",
        receiverName: "Supplier Beta AI COO",
        dialogue: "Sourcing recovery active. Redirecting inquiry and context logs to backup Supplier Beta AI COO.",
        capability: "Context Share",
        reason: "Backup inventory check",
        action: "Buyer AI COO fails over to Supplier Beta.",
        narration: "Buyer AI COO fails over to Supplier Beta.",
        apiCallName: "POST /api/v1/share/create",
        apiCallMethod: "POST",
        apiCallPath: "/share/create",
        payload: { scope: "folders", folderIds: [3], label: "Backup quotation logs context" },
        glowNode: "ceo",
        pulseType: "share",
        badge: "Beta Query"
      },
      {
        stepIndex: 4,
        source: "ceo",
        target: "devops",
        senderName: "Supplier Beta AI COO",
        receiverName: "Warehouse AI COO",
        dialogue: "Sourcing request accepted. Verifying Tokyo shipping slots with Warehouse AI COO.",
        capability: "Routing",
        reason: "Capacity verification",
        action: "Supplier Beta coordinates packing and dispatch slot with Warehouse.",
        narration: "Supplier Beta coordinates packing and dispatch slot with Warehouse.",
        apiCallName: "POST /api/v1/accumulate",
        apiCallMethod: "POST",
        apiCallPath: "/accumulate",
        payload: { files: [{ path: "Beta/solar-slots.md", content: "200 panels ready" }] },
        glowNode: "devops",
        pulseType: "context",
        badge: "Dock Reserved"
      },
      {
        stepIndex: 5,
        source: "devops",
        target: "operations",
        senderName: "Warehouse AI COO",
        receiverName: "Logistics AI COO",
        dialogue: "Express dispatch dock reserved. Requesting express courier scheduler tool.",
        capability: "Permission",
        reason: "Dispatch carrier booking",
        action: "Warehouse requests Logistics to book express delivery carrier.",
        narration: "Warehouse requests Logistics to book express delivery carrier.",
        apiCallName: "POST /api/v1/tools",
        apiCallMethod: "POST",
        apiCallPath: "/tools",
        payload: { tool: "schedule_priority_carrier" },
        glowNode: "operations",
        pulseType: "message",
        badge: "Logistics Sched"
      },
      {
        stepIndex: 6,
        source: "operations",
        target: "customer",
        senderName: "Logistics AI COO",
        receiverName: "Customer Client",
        dialogue: "Priority dispatch completed. Solar Panels scheduled for Tokyo Harbor delivery.",
        capability: "Briefing",
        reason: "Procurement routing resolved",
        action: "Logistics AI COO confirms dispatch and updates Customer Agent.",
        narration: "Logistics AI COO confirms dispatch and notifies Customer Agent.",
        apiCallName: "POST /api/v1/briefing",
        apiCallMethod: "POST",
        apiCallPath: "/briefing",
        payload: { summary: "200 Solar Panels dispatched via backup Supplier Beta." },
        glowNode: "customer",
        pulseType: "complete",
        badge: "Dispatched"
      }
    ]
  }
];
